### ISSUE TITLE
Tracebacks in gst_tf_detection.py and base.py

### ISSUE THREAD

**Issue by krupal-59** [jackersson/gst-plugins-tf#2]
when I executes "run_examples.sh", Video starts playing but I am having following tracebacks:
Traceback (most recent call last):
  File "/home/krupal/gst-plugins-tf/gst/python/gst_tf_detection.py", line 363, in do_set_property
    self._do_set_model(from_config_file(value))
  File "/home/krupal/gst-plugins-tf/gst/python/gst_tf_detection.py", line 281, in from_config_file
    return TfObjectDetectionModel(**load_config(filename))
  File "/home/krupal/gst-plugins-tf/gst/python/gst_tf_detection.py", line 171, in __init__
    self.config = self._config_schema.check(kwargs or {})
  File "/home/krupal/gst-plugins-tf/venv/lib/python3.6/site-packages/trafaret/base.py", line 110, in check
    return self.transform(value, context=context)
  File "/home/krupal/gst-plugins-tf/venv/lib/python3.6/site-packages/trafaret/base.py", line 1064, in transform
    for k, v, names in key(value, context=context):
  File "/home/krupal/gst-plugins-tf/venv/lib/python3.6/site-packages/trafaret/base.py", line 893, in __call__
    result = self.trafaret(self.get_data(data, default), context=context)
  File "/home/krupal/gst-plugins-tf/venv/lib/python3.6/site-packages/trafaret/base.py", line 142, in __call__
    return self.check(val, context=context)
  File "/home/krupal/gst-plugins-tf/venv/lib/python3.6/site-packages/trafaret/base.py", line 110, in check
    return self.transform(value, context=context)
  File "/home/krupal/gst-plugins-tf/venv/lib/python3.6/site-packages/trafaret/base.py", line 315, in transform
    return self.other(res, context=context)
  File "/home/krupal/gst-plugins-tf/venv/lib/python3.6/site-packages/trafaret/base.py", line 142, in __call__
    return self.check(val, context=context)
  File "/home/krupal/gst-plugins-tf/venv/lib/python3.6/site-packages/trafaret/base.py", line 110, in check
    return self.transform(value, context=context)
  File "/home/krupal/gst-plugins-tf/venv/lib/python3.6/site-packages/trafaret/base.py", line 1272, in transform
    res = self.fn(value)
  File "/home/krupal/gst-plugins-tf/gst/python/gst_tf_detection.py", line 58, in _parse_device
    raise ValueError('Specified "{}" device but GPU not available'.format(device))
ValueError: Specified "GPU|CPU" device but GPU not available
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Redistribute latency...
Redistribute latency...
0:00:05.586413615 25649 0x7fbf0c015720 WARN                  python gst_tf_detection.py:331:do_transform_ip: No model speficied for <gst_tf_detection.GstTfDetectionPluginPy object at 0x7fbf4f113fc0 (gst_tf_detection+GstTfDetectionPluginPy at 0x55b42dd14130)>. Plugin working in passthrough mode
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
0:00:05.610948496 25649 0x7fbf0c015720 WARN                  python gst_tf_detection.py:331:do_transform_ip: No model speficied for <gst_tf_detection.GstTfDetectionPluginPy object at 0x7fbf4f113fc0 (gst_tf_detection+GstTfDetectionPluginPy at 0x55b42dd14130)>. Plugin working in passthrough mode
![tracebacks](https://user-images.githubusercontent.com/61958780/81033106-dad47880-8eaf-11ea-824f-dd02cf958bec.png)

**Comment by jackersson** [comment]
Hi, 

There was a small mistake in code. I believe I fixed it ([commit](https://github.com/jackersson/gst-plugins-tf/commit/75de9b46f07b8ec6f78af01cf80afefa65d11af6))

**Comment by krupal-59** [comment]
Sorry but no output
![Screenshot from 2020-05-05 13-29-37](https://user-images.githubusercontent.com/61958780/81045805-97403580-8ed4-11ea-9833-48dfdbed2e30.png)
:

WARNIN | tensorflow           | 05.05 13:24:01.245 | MainThread | From /home/krupal/gst-plugins-tf/gst/python/gst_tf_detection.py:68: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNIN | tensorflow           | 05.05 13:24:01.245 | MainThread | From /home/krupal/gst-plugins-tf/gst/python/gst_tf_detection.py:82: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

WARNIN | tensorflow           | 05.05 13:24:04.269 | MainThread | From /home/krupal/gst-plugins-tf/gst/python/gst_tf_detection.py:68: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

WARNIN | tensorflow           | 05.05 13:24:04.269 | MainThread | From /home/krupal/gst-plugins-tf/gst/python/gst_tf_detection.py:82: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

INFO   | gst_python           | 05.05 13:24:04.308 | MainThread | Starting TfObjectDetectionModel ...
**Traceback (most recent call last):**
  File "/home/krupal/gst-plugins-tf/gst/python/gst_tf_detection.py", line 361, in do_set_property
    self._do_set_model(from_config_file(value))
  File "/home/krupal/gst-plugins-tf/gst/python/gst_tf_detection.py", line 378, in _do_set_model
    self.model.startup()
  File "/home/krupal/gst-plugins-tf/gst/python/gst_tf_detection.py", line 208, in startup
    per_process_gpu_memory_fraction=self.config['per_process_gpu_memory_fraction'])
  File "/home/krupal/gst-plugins-tf/gst/python/gst_tf_detection.py", line 77, in create_config
    config.device_count = {'GPU': 0}
AttributeError: Assignment not allowed to repeated field "device_count" in protocol message object.
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Redistribute latency...
Redistribute latency...
ERROR  | root                 | 05.05 13:24:04.495 | Dummy-1 | Error <gst_tf_detection.GstTfDetectionPluginPy object at 0x7fbdd7d08ee8 (gst_tf_detection+GstTfDetectionPluginPy at 0x563cb79c0130)>: 'NoneType' object has no attribute 'run'
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR  | root                 | 05.05 13:24:04.521 | Dummy-1 | Error <gst_tf_detection.GstTfDetectionPluginPy object at 0x7fbdd7d08ee8 (gst_tf_detection+GstTfDetectionPluginPy at 0x563cb79c0130)>: 'NoneType' object has no attribute 'run'
ERROR  | root                 | 05.05 13:24:04.566 | Dummy-1 | Error <gst_tf_detection.GstTfDetectionPluginPy object at 0x7fbdd7d08ee8 (gst_tf_detection+GstTfDetectionPluginPy at 0x563cb79c0130)>: 'NoneType' object has no attribute 'run'
![Screenshot from 2020-05-05 13-29-37](https://user-images.githubusercontent.com/61958780/81045853-b6d75e00-8ed4-11ea-9023-2d1b75ac030e.png)

**Comment by jackersson** [comment]
Fixed here: [commit](https://github.com/jackersson/gst-plugins-tf/commit/04166656e172232dc19d74bff4f5ad4aff7275be)

**Comment by krupal-59** [comment]
@jackersson Thank you sir,
Done.
